name: Release Build and Deploy

on:
  # Triggers when a new GitHub Release is published
  release:
    types: [published] 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run my custom Java action
        uses: madraceee/repo-scanner@v1
        with:
          server-url: https://85562d5f6ecc.ngrok-free.app/api/scan
